{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "task = 'shortest_path'\n",
    "filename = task+'_result_gpt4.json'\n",
    "with open(filename, 'r', encoding='utf-8') as f:\n",
    "    datas=json.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "filename1 = task+'_test.json'\n",
    "with open(filename1, 'r', encoding='utf-8') as f:\n",
    "    gt=json.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "300\n",
      "300\n",
      "{'input_prompt': 'Given an undirected graph as follows:\\nNode 8 is connected to nodes 4 (weight: 6), 2 (weight: 2), 1 (weight: 8).\\nNode 4 is connected to nodes 8 (weight: 6), 2 (weight: 6), 3 (weight: 4).\\nNode 2 is connected to nodes 8 (weight: 2), 4 (weight: 6), 5 (weight: 4), 0 (weight: 1), 6 (weight: 8), 1 (weight: 2).\\nNode 1 is connected to nodes 8 (weight: 8), 2 (weight: 2), 5 (weight: 5), 0 (weight: 6), 6 (weight: 10), 7 (weight: 7), 3 (weight: 7).\\nNode 3 is connected to nodes 4 (weight: 4), 1 (weight: 7).\\nNode 5 is connected to nodes 2 (weight: 4), 1 (weight: 5).\\nNode 0 is connected to nodes 2 (weight: 1), 1 (weight: 6).\\nNode 6 is connected to nodes 2 (weight: 8), 1 (weight: 10).\\nNode 7 is connected to node 1 (weight: 7).\\n\\nCalculate the length of the shortest path from node 5 to node 1.', 'answer': 5}\n"
     ]
    }
   ],
   "source": [
    "print(len(datas))\n",
    "print(len(gt))\n",
    "print(gt[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "import io\n",
    "import sys\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-16 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 46, in <module>\n",
      "  File \"<string>\", line 39, in dijkstra\n",
      "KeyError: 1\n",
      "Exception in thread Thread-18 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 35, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 9\n",
      "Exception in thread Thread-36 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 33, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 11\n",
      "Exception in thread Thread-37 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 35, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 6\n",
      "Exception in thread Thread-68 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 4\n",
      "Exception in thread Thread-82 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 17, in dijkstra\n",
      "KeyError: 0\n",
      "Exception in thread Thread-84 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 40, in <module>\n",
      "  File \"<string>\", line 17, in dijkstra\n",
      "KeyError: 6\n",
      "Exception in thread Thread-92 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 49, in <module>\n",
      "  File \"<string>\", line 42, in dijkstra\n",
      "KeyError: 5\n",
      "Exception in thread Thread-97 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 32, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " 11\n",
      " 24\n",
      " 20\n",
      " 7\n",
      " 7\n",
      " 8\n",
      " 9\n",
      " 24\n",
      " 12\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-107 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 31, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 4\n",
      "Exception in thread Thread-134 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 15, in dijkstra\n",
      "KeyError: 4\n",
      "Exception in thread Thread-136 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 2\n",
      "Exception in thread Thread-141 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 35, in <module>\n",
      "  File \"<string>\", line 17, in dijkstra\n",
      "KeyError: 1\n",
      "Exception in thread Thread-168 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 17, in dijkstra\n",
      "KeyError: 5\n",
      "Exception in thread Thread-188 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 32, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 2\n",
      "Exception in thread Thread-217 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 11\n",
      "Exception in thread Thread-232 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 45, in <module>\n",
      "  File \"<string>\", line 38, in dijkstra\n",
      "KeyError: 7\n",
      "Exception in thread Thread-240 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " 10\n",
      " 6\n",
      " 4\n",
      " 10\n",
      " 16\n",
      " 17\n",
      " 12\n",
      " 6\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 33, in <module>\n",
      "  File \"<string>\", line 17, in dijkstra\n",
      "KeyError: 2\n",
      "Exception in thread Thread-243 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 47, in <module>\n",
      "  File \"<string>\", line 40, in dijkstra\n",
      "KeyError: 3\n",
      "Exception in thread Thread-252 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 3\n",
      "Exception in thread Thread-253 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 37, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 5\n",
      "Exception in thread Thread-270 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 10\n",
      "Exception in thread Thread-285 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 39, in <module>\n",
      "  File \"<string>\", line 17, in dijkstra\n",
      "KeyError: 6\n",
      "Exception in thread Thread-292 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2349271/2305305801.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 13, in dijkstra\n",
      "KeyError: 9\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " 3\n",
      " 15\n",
      " 8\n",
      " 7\n",
      " 10\n",
      " 6\n",
      " 3\n"
     ]
    }
   ],
   "source": [
    "error_cnt = 0\n",
    "correct_cnt = 0\n",
    "import threading\n",
    "import re\n",
    "\n",
    "class TimeoutException(Exception):\n",
    "    pass\n",
    "\n",
    "def run_with_timeout(code, timeout=15):\n",
    "    # 定义执行代码的函数\n",
    "    def target():\n",
    "        exec(code, globals(), globals())\n",
    "\n",
    "    thread = threading.Thread(target=target)\n",
    "    thread.start()\n",
    "    thread.join(timeout)\n",
    "\n",
    "    if thread.is_alive():\n",
    "        raise TimeoutException(\"Code execution exceeded timeout limit.\")\n",
    "\n",
    "for i, (key,value) in enumerate(datas.items()):\n",
    "    text = value['gpt4']\n",
    "    code = re.sub(r'^```python\\n|```$', '', text, flags=re.MULTILINE)\n",
    "    ans = gt[i]['answer']\n",
    "\n",
    "    # 创建一个 StringIO 对象来捕获输出\n",
    "    output = io.StringIO()\n",
    "\n",
    "    # 重定向 sys.stdout\n",
    "    old_stdout = sys.stdout\n",
    "    sys.stdout = output\n",
    "\n",
    "    try:\n",
    "        run_with_timeout(code,timeout=5)\n",
    "    except TimeoutException as e:\n",
    "        error_cnt = error_cnt + 1\n",
    "        print(e)\n",
    "        continue\n",
    "    except:\n",
    "        sys.stdout = old_stdout\n",
    "        print(code)\n",
    "        error_cnt = error_cnt + 1\n",
    "        continue\n",
    "    finally:\n",
    "        sys.stdout = old_stdout\n",
    "    \n",
    "\n",
    "    # 获取输出内容\n",
    "    output_content = output.getvalue()\n",
    "    output_content = str(output_content).strip()\n",
    "    # print(\"Captured Output:\")\n",
    "    \n",
    "    if output_content == 'yes' or output_content == 'True':\n",
    "        output_content = 'Yes'\n",
    "    elif output_content == 'no' or output_content == 'False':                                 \n",
    "        output_content = 'No'\n",
    "\n",
    "    if output_content.strip() == str(ans).strip():\n",
    "         correct_cnt = correct_cnt + 1\n",
    "    else:\n",
    "        #print(code)\n",
    "        print(output_content,ans)\n",
    "        # print(code)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "276\n"
     ]
    }
   ],
   "source": [
    "print(error_cnt)\n",
    "print(correct_cnt)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.92\n"
     ]
    }
   ],
   "source": [
    "print(correct_cnt/len(datas))\n",
    "#max tokens是"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1,3,5,2,4\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "output_content = \"[1,3,5,2,4]\"\n",
    "pattern = r\"[\\{\\[]([^}\\]]*)[\\}\\]]\"\n",
    "match1 = re.search(pattern, output_content)\n",
    "\n",
    "\n",
    "if match1:\n",
    "    content_output = match1.group(1)\n",
    "    \n",
    "print(content_output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0, 1, 2, 3, 4, 10, 7\n",
      "[0, 1, 2, 3, 4, 7, 10]\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "\n",
    "text = \"{0, 1, 2, 3, 4, 10, 7}\"\n",
    "pattern = r\"[\\{\\[]([^}\\]]*)[\\}\\]]\"\n",
    "match = re.search(pattern, text)\n",
    "\n",
    "if match:\n",
    "    content = match.group(1)\n",
    "    print(content)  # 输出: 0, 1, 2, 3, 4, 6, 7\n",
    "    numbers = list(map(int, content.split(',')))\n",
    "    numbers.sort()\n",
    "    print(numbers)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
